name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch
  workflow_dispatch: # Allows manual triggers

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (if it's a Node.js project; adapt for other environments)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify your required Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build project
        run: npm run build # Ensure this command creates the files for deployment

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
